- name: Replace a container of upload-service
  hosts: all
  become: false
  tasks:
    - name: Get infos on 'upload-service' container
      docker_container_info:
        name: upload-service
      register: result
      
    - name: Does container exist?
      debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"
      
    - name: Stop a container
      community.docker.docker_container:
        name: upload-service
        state: stopped
      when: result.exists

    - name: Remove container
      community.docker.docker_container:
        name: upload-service
        state: absent
      when: result.exists

    - name: Remove image
      community.docker.docker_image:
        state: absent
        name: splendidpdf/upload-service
        tag: 0.0.1-SNAPSHOT
      when: result.exists

    - name: Run upload service
      community.docker.docker_container:
        name: upload-service
        image: splendidpdf/upload-service:0.0.1-SNAPSHOT
        state: started
        pull: true
        ports:
          - "9001:9001"
          - "8021:8021"
        env:
          SPRING_CONFIG_IMPORT: "configserver:http://51.250.102.12:8888"
          SPRING_CLOUD_CONFIG_LABEL: "develop"
