- name: Replace a container of review-service
  hosts: all
  become: false
  tasks:
    - name: Stop a container
      community.docker.docker_container:
        name: review-service
        state: stopped

    - name: Remove container
      community.docker.docker_container:
        name: review-service
        state: absent

    - name: Remove image
      community.docker.docker_image:
        state: absent
        name: splendidpdf/review-service
        tag: 0.0.1-SNAPSHOT

    - name: Run review service
      community.docker.docker_container:
        name: review-service
        image: splendidpdf/review-service:0.0.1-SNAPSHOT
        state: started
        pull: true
        ports:
          - "8082:8082"
          - "8002:8002"
        env:
          SPRING_CONFIG_IMPORT: "configserver:http://51.250.102.12:8888"
          SPRING_CLOUD_CONFIG_LABEL: "develop"