- name: Replace a container of authorization-service
  hosts: all
  become: false
  tasks:
    - name: Get infos on 'authorization-service' container
      docker_container_info:
        name: authorization-service
      register: result

    - name: Does container exist?
      debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

    - name: Stop a container
      community.docker.docker_container:
        name: authorization-service
        state: stopped
      when: result.exists

    - name: Remove container
      community.docker.docker_container:
        name: authorization-service
        state: absent
      when: result.exists

    - name: Remove image
      community.docker.docker_image:
        state: absent
        name: splendidpdf/authorization-server
        tag: 0.0.1-SNAPSHOT
      when: result.exists

    - name: Run auth service
      community.docker.docker_container:
        name: authorization-service
        image: splendidpdf/authorization-server:0.0.1-SNAPSHOT
        state: started
        pull: true
        ports:
          - "9000:9000"
        env:
          SPRING_CONFIG_IMPORT: "configserver:http://51.250.102.12:8888"
          SPRING_CLOUD_CONFIG_LABEL: "develop"