- name: Replace a container of config-server
  hosts: all
  become: false
  tasks:
    - name: Get infos on 'config-server' container
      docker_container_info:
        name: config-server
      register: result

    - name: Does container exist?
      debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

    - name: Stop a container
      community.docker.docker_container:
        name: config-server
        state: stopped
      when: result.exists

    - name: Remove container
      community.docker.docker_container:
        name: config-server
        state: absent
      when: result.exists

    - name: Remove image
      community.docker.docker_image:
        state: absent
        name: splendidpdf/config-server
        tag: 0.0.1-SNAPSHOT
      when: result.exists

    - name: Run config server
      community.docker.docker_container:
        name: config-server
        image: splendidpdf/config-server:0.0.1-SNAPSHOT
        state: started
        pull: true
        ports:
          - "8888:8888"