- name: Deployment of containers on server
  hosts: all
  become: false
  tasks:
    - name: Run config server
      community.docker.docker_container:
        name: config-server
        image: splendidpdf/config-server:0.0.1-SNAPSHOT
        state: started
        pull: true
        ports:
          - "8888:8888"

    - name: Run user service
      community.docker.docker_container:
        name: user-service
        image: splendidpdf/user-service:0.0.1-SNAPSHOT
        state: started
        pull: true
        ports:
          - "8080:8080"
          - "8000:8000"
        env:
          SPRING_CONFIG_IMPORT: "configserver:http://51.250.102.12:8888"
          SPRING_CLOUD_CONFIG_LABEL: "develop"

    - name: Run order service
      community.docker.docker_container:
        name: order-service
        image: splendidpdf/order-service:0.0.1-SNAPSHOT
        state: started
        pull: true
        ports:
          - "8081:8081"
          - "8001:8001"
        env:
          SPRING_CONFIG_IMPORT: "configserver:http://51.250.102.12:8888"
          SPRING_CLOUD_CONFIG_LABEL: "develop"

    - name: Run product service
      community.docker.docker_container:
        name: product-service
        image: splendidpdf/product-service:0.0.1-SNAPSHOT
        state: started
        pull: true
        ports:
          - "9090:9090"
          - "8020:8020"
        env:
          SPRING_CONFIG_IMPORT: "configserver:http://51.250.102.12:8888"
          SPRING_CLOUD_CONFIG_LABEL: "develop"

    - name: Run seller service
      community.docker.docker_container:
        name: seller-info-service
        image: splendidpdf/seller-info-service:0.0.1-SNAPSHOT
        state: started
        pull: true
        ports:
          - "8085:8085"
          - "8005:8005"
        env:
          SPRING_CONFIG_IMPORT: "configserver:http://51.250.102.12:8888"
          SPRING_CLOUD_CONFIG_LABEL: "develop"

    - name: Run review service
      community.docker.docker_container:
        name: review-service
        image: splendidpdf/review-service:0.0.1-SNAPSHOT
        state: started
        pull: true
        ports:
          - "8082:8082"
          - "8002:8002"
        env:
          SPRING_CONFIG_IMPORT: "configserver:http://51.250.102.12:8888"
          SPRING_CLOUD_CONFIG_LABEL: "develop"

    - name: Run upload service
      community.docker.docker_container:
        name: upload-service
        image: splendidpdf/upload-service:0.0.1-SNAPSHOT
        state: started
        pull: true
        ports:
          - "9001:9001"
          - "8021:8021"
        env:
          SPRING_CONFIG_IMPORT: "configserver:http://51.250.102.12:8888"
          SPRING_CLOUD_CONFIG_LABEL: "develop"

    - name: Run auth service
      community.docker.docker_container:
        name: authorization-service
        image: splendidpdf/authorization-server:0.0.1-SNAPSHOT
        state: started
        pull: true
        ports:
          - "9000:9000"
        env:
          SPRING_CONFIG_IMPORT: "configserver:http://51.250.102.12:8888"
          SPRING_CLOUD_CONFIG_LABEL: "develop"

    - name: Run api gateway service
      community.docker.docker_container:
        name: api-gateway-service
        image: splendidpdf/api-gateway-service:0.0.1-SNAPSHOT
        state: started
        pull: true
        ports:
          - "7777:7777"
          - "7700:7700"
        env:
          SPRING_CONFIG_IMPORT: "configserver:http://51.250.102.12:8888"
          SPRING_CLOUD_CONFIG_LABEL: "develop"

    - name: Run grafana agent
      community.docker.docker_container:
        name: grafana-agent
        image: grafana/agent:v0.33.0
        state: started
        pull: true
        volumes:
          - /tmp/agent:/etc/agent/data
          - /home/marketplace/agent-config.yaml:/etc/agent/agent.yaml