- name: Replace a container of product-service
  hosts: all
  become: false
  tasks:
    - name: Stop a container
      community.docker.docker_container:
        name: product-service
        state: stopped

    - name: Remove container
      community.docker.docker_container:
        name: product-service
        state: absent

    - name: Remove image
      community.docker.docker_image:
        state: absent
        name: splendidpdf/product-service
        tag: 0.0.1-SNAPSHOT

    - name: Run product service
      community.docker.docker_container:
        name: product-service
        image: splendidpdf/product-service:0.0.1-SNAPSHOT
        state: started
        pull: true
        ports:
          - "9090:9090"
          - "8020:8020"
        env:
          SPRING_CONFIG_IMPORT: "configserver:http://51.250.102.12:8888"
          SPRING_CLOUD_CONFIG_LABEL: "develop"