- name: Replace a container of user-service
  hosts: all
  become: false
  tasks:
    - name: Stop a container
      community.docker.docker_container:
        name: user-service
        state: stopped

    - name: Remove container
      community.docker.docker_container:
        name: user-service
        state: absent

    - name: Remove image
      community.docker.docker_image:
        state: absent
        name: splendidpdf/user-service
        tag: 0.0.1-SNAPSHOT

    - name: Run user service
      community.docker.docker_container:
        name: user-service
        image: splendidpdf/user-service:0.0.1-SNAPSHOT
        state: started
        pull: true
        ports:
          - "8080:8080"
          - "8000:8000"
        env:
          SPRING_CONFIG_IMPORT: "configserver:http://51.250.102.12:8888"
          SPRING_CLOUD_CONFIG_LABEL: "develop"